# Generated by Django 4.2.27 on 2026-01-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_price_per_unit_ingredient_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1, max_length=10, null=True),
        ),
    ]
